name: Generate Snake Animation

on:
  schedule:
    # Ejecuta el flujo de trabajo una vez al día
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Clone repository
        uses: actions/checkout@v2

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Instala las dependencias necesarias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests

      # Genera la animación de la serpiente
      - name: Generate snake animation
        run: |
          curl -o github-contribution-grid-snake.svg https://github.com/Platane/snk/raw/output/github-contribution-grid-snake.svg
          mv github-contribution-grid-snake.svg ./output/github-contribution-grid-snake.svg

      # Subir el archivo generado a la rama `output`
      - name: Push to output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: ./output/github-contribution-grid-snake.svg
